vcs -full64 -sverilog \
  +incdir+/home/mickey/ara/hardware/deps/common_cells/include \
  +incdir+/home/mickey/ara/hardware/deps/cva6/include \
  +incdir+/home/mickey/ara/hardware/include \
  ../../deps/cva6/core/include/config_pkg.sv \
  ../../deps/cva6/core/include/cv64a6_imafdcv_sv39_config_pkg.sv \
  ../../deps/cva6/vendor/pulp-platform/common_cells/include/common_cells/registers.svh \
  ../../deps/cva6/core/include/riscv_pkg.sv \
  ../../deps/cva6/core/include/ariane_pkg.sv \
  ../../deps/fpnew/src/fpnew_pkg.sv \
  ../../deps/axi/src/axi_pkg.sv \
  ../../deps/common_cells/src/cf_math_pkg.sv \
  ../../deps/cva6/vendor/pulp-platform/tech_cells_generic/src/rtl/tc_clk.sv \
  ../../deps/cva6/vendor/pulp-platform/common_cells/src/spill_register_flushable.sv \
  ../../deps/fpnew/src/fpnew_cast_multi.sv \
  ../../deps/cva6/vendor/openhwgroup/cvfpu/src/fpnew_rounding.sv \
  ../../deps/cva6/vendor/openhwgroup/cvfpu/src/fpnew_fma.sv \
  ../../deps/fpu_div_sqrt_mvp/hdl/defs_div_sqrt_mvp.sv \
  ../../deps/fpu_div_sqrt_mvp/hdl/iteration_div_sqrt_mvp.sv \
  ../../deps/fpu_div_sqrt_mvp/hdl/control_mvp.sv \
  ../../deps/fpu_div_sqrt_mvp/hdl/norm_div_sqrt_mvp.sv \
  ../../deps/fpu_div_sqrt_mvp/hdl/preprocess_mvp.sv \
  ../../deps/fpu_div_sqrt_mvp/hdl/nrbd_nrsc_mvp.sv \
  ../../deps/fpu_div_sqrt_mvp/hdl/div_sqrt_top_mvp.sv \
  ../../deps/fpu_div_sqrt_mvp/hdl/div_sqrt_mvp_wrapper.sv \
  ../../deps/cva6/vendor/openhwgroup/cvfpu/src/fpnew_divsqrt_multi.sv \
  ../../deps/cva6/vendor/openhwgroup/cvfpu/src/fpnew_noncomp.sv \
  ../../deps/cva6/vendor/openhwgroup/cvfpu/src/fpnew_classifier.sv \
  ../../deps/cva6/vendor/openhwgroup/cvfpu/src/fpnew_opgroup_fmt_slice.sv \
  ../../deps/cva6/vendor/openhwgroup/cvfpu/src/fpnew_opgroup_multifmt_slice.sv \
  ../../deps/fpnew/src/fpnew_opgroup_block.sv \
  ../../deps/common_cells/src/rr_arb_tree.sv \
  ../../deps/fpnew/src/fpnew_top.sv \
  ../../deps/cva6/vendor/pulp-platform/common_cells/src/spill_register.sv \
  ../../include/rvv_pkg.sv \
  ../../deps/cva6/core/include/acc_pkg.sv \
  ../../deps/cva6/vendor/pulp-platform/common_cells/src/lzc.sv \
  ../../include/ara_pkg.sv \
  power_gating_generic.sv \
  simd_mul.sv \
  simd_tmac.sv \
  simd_pe.sv \
  arch_showdown_tb.sv \
  -o simv_showdown